### ISSUE TITLE
Enhancement idea: Involving how Key-usage works

### ISSUE THREAD

**Issue by Roobotics** [nomnomab/lc-turret-key#2]
Maps spawn with a set number of keys, there are many mods that add additional turrets indoors as well as outdoors. 'OverprotectedFacilities' 'HazardsOutside' etc!

Having a configurable % 0 to 100 would be a great way to add a 'ChanceOfBreaking', so you can either guarantee a break/keep/ or have a statistical chance to help deal with the amount of turrets you're likely to encounter.

Consider adding a config file option for the % chance of usage on a turret to consume the key.

There are mods like 'MasterKey' which will prevent destroying the key, but it does this for doors as well, which is **not** the intention here. Additionally there are other mods that try to do this, 'GeneralImprovements' has a config option for 'KeysHaveInfiniteUses' and that one only works on how doors consume them, from my testing. So that's also the polar opposite of this idea.

Upon finding a locked door and only having one key, a player should be making a conscious choice about unlocking it to proceed, but also losing their disarming tool (the key).

By making it a percent it has some benefits, Rather than a simple KEEP/BREAK system, you could further gamify how keys are used, "Is this turret really the one I can't dodge if I break my key here? etc. This adds a fun dynamic so I thought I'd share the idea. Being able to disable turrets in Mods like 'OverprotectedFacilities' is crucial for survival(sometimes 3 turrets in a room, etc!), but being able to 100% disable them doesn't feel aligned to the chaotic gameplay either, just as disarming mines by tossing stun grenades across them is a janky business, sometimes things need to not go quite as planned, and RNG is a good way to do that!

Thanks for hearing me out, also very happy your mod exists in the first place! Mods like 'Kill_It_With_Shovel' to temporarily disable turrets with the shovel-hit, are **completely broken** by popular mods like 'FairAI' which is a bummer, but understandable. I've been trying to piece together a mod list where the facility itself is more a threat than the monsters, but sometimes the RNG placement of turrets is just.. bad.. so a way to deal with them is required! Speaking of.. I'd gladly use a key a second time, or guaranteed to break, to remove a disabled turret body, they very much can block entire doorways and be 100% impassible, I don't know of any mods that can deal with this problem still at this time, so might as well mention it now. Cheers!

**Comment by nomnomab** [comment]
Sounds good! I'll look into adding it when I get a chance 👍

**Comment by Roobotics** [comment]
I'm happy to report that this mechanic is working **really well** so far! Rather than running out of keys and coming to impossible to traverse rooms, or simply ending up with "too many keys" like with the masterkey mod caused, the balance on this has been flawless from the very first trial. I've barely been making it through and it's certainly added that extra layer of unpredictable challenge. Even with the keep/drop rate at something like 80/20, it's a real gamble to run down hallways with 3 turrets and a single key. Thanks! Also I can verify that firing turrets that are then keyed, have stopped firing at the ground endlessly per the other issue, and also still no issues with other mods like FairAI that I've noticed. 👍 Amazing.
