### ISSUE TITLE
thunderstore listing

### ISSUE THREAD

**Issue by bmatusiak** [nomnomab/lc-turret-key#7]
well it looks like it disappeared.

https://thunderstore.io/c/lethal-company/p/NomnomAB/TurretKey/

https://thunderstore.io/c/lethal-company/p/NomnomAB/

**Comment by nomnomab** [comment]
Seems switching to `LethalCompany.GameLibs.Steam` for the game dlls made it emit dlls into the publish directory. So the package was rejected... not really sure on why it is doing that now but I'm looking into it.

**Comment by nomnomab** [comment]
Seems I had to put `PrivateAssets="All"` onto the package ref to have it not include them all. I guess the prior package had it but I didn't know about it haha. Resolving it with TS now.

**Comment by nomnomab** [comment]
Alright it's back up 👍 Apologies for that
